apiVersion: v1
kind: Namespace
metadata:
  name: service1
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
  namespace: service1
spec:
  selector:
    app: service-1
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: <acr>.azurecr.io/service-1
        ports:
        - containerPort: 80
