apiVersion: v1
kind: Namespace
metadata:
  name: service2
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: service-2
  namespace: service2
spec:
  selector:
    app: service-2
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  namespace: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
      - name: service-2
        image: <acr>.azurecr.io/service-1
        ports:
        - containerPort: 80
